# Generated by Django 3.2.15 on 2024-02-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
    ]
