# Generated by Django 3.2.15 on 2024-02-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0003_alter_register_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=20)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='contactus',
        ),
    ]
